### ISSUE TITLE
Use nova_get_setting into  config/* files ?

### ISSUE THREAD

**Issue by scramatte** [outl1ne/nova-settings#113]
Hello,

I would like to use nova_get_setting into  config/* files   for notifications, mail and ldap settings
I've got the following error

`Call to a member function connection() on null
`
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/188766/164408671-8eec1b1a-a6f9-445b-8032-e0b60369bf70.png">

Thank you for the help

**Comment by Tarpsvo** [comment]
You can't use nova-settings in the config files. The nova-settings depends on a database and config files are created before the database connection is set up (which is also set up using config files, so it's a loop pretty much).

**Comment by nathan-io** [comment]
We wanted to use these settings in config, so the approach was to create a helper to safely check for the value, then use it in our service providers to set config values:

Helper:

```
    function safe_nova_get_setting($settingName, $fallbackValue) {
        $return = $fallbackValue;
        if(Schema::hasTable('nova_settings')) {
            try {
                $return = nova_get_setting($settingName, $fallbackValue);
            } catch (Throwable $e) {}
        }
        return $return;
    }
```

In `AppServiceProvider@boot`:

```
        config([
            'app.timezone' => safe_nova_get_setting('APP_TIMEZONE', 'UTC'),
            // ...
        ]);
```

This is working fine so far, but hasn't been thoroughly tested.
