### ISSUE TITLE
No content displayed for Image or file fields 

### ISSUE THREAD

**Issue by scramatte** [outl1ne/nova-settings#116]
Hello,

I've created settings that use Image and File fields. Files and images are uploaded properly  (I can see them into storage folder) but no link or thumbnail is displayed on the settings pages.  Basically we don't know that a file has already been uploaded.

Any idea?

Regards

**Comment by BachirBichri** [comment]
Hello @scramatte  did you resolve that issue ?

**Comment by chrisvasey** [comment]
I am still having an issue with this one.
Is it a known issue with the package?
