### ISSUE TITLE
Deleting an image doesn't actually remove the image from the filesystem

### ISSUE THREAD

**Issue by bluec** [outl1ne/nova-settings#127]
The [`\OptimistDigital\NovaSettings\Http\Controllers\SettingsController::deleteImage`](https://github.com/outl1ne/nova-settings/blob/86ede484b9269b206bb83cf81ef77285cdd5a5c1/src/Http/Controllers/SettingsController.php#L111) method doesn't actually delete the image from the filesystem it only sets the setting value to null.

We could force a delete like this example below but it would be better to hook into the Nova Image field instance and delete it that way, does anyone have any idea how to do that? I will file a PR if we can figure it out!

```php
Storage::disk('public')->delete($existingRow->value);
```

**Comment by bluec** [comment]
Whoops just realised this is pretty much a dupe of #125 - I had searched for "image" in the issues so not noticed that issue was already open.

**Comment by Tarpsvo** [comment]
Thanks for reporting this! Fixed in version 5.0.3. ;)

**Comment by bluec** [comment]
@Tarpsvo thanks, would you consider back-porting this to v3 branch too? I could make a PR if you like.

**Comment by Tarpsvo** [comment]
Heya! Released the Nova 3 fix in version 3.5.7.

**Comment by bluec** [comment]
Thank you @Tarpsvo amazing!
