### ISSUE TITLE
Textarea does not render helper text

### ISSUE THREAD

**Issue by jaxramus** [outl1ne/nova-settings#128]
\Outl1ne\NovaSettings\NovaSettings::addSettingsFields([
      Panel::make('Settings', [
        Textarea::make('New Lead Emails')
          ->alwaysShow()
          ->help('
            Enter one email address per line.
        '),

        Textarea::make('New Contact Emails')
          ->alwaysShow()
          ->help('
            Enter one email address per line.
        '),
      ]),

The textareas show up and work, but they do not show the help text.

**Comment by Tarpsvo** [comment]
What's your Nova and nova-settings version? The help texts seem to work for me.

**Comment by mberatsanli** [comment]
@jaxramus check out my fix https://github.com/outl1ne/nova-settings/pull/135

**Comment by Tarpsvo** [comment]
Thanks to @mberatsanli for the PR! The fix was released in version 5.0.5.
