### ISSUE TITLE
Availability to cache settings

### ISSUE THREAD

**Issue by romainvausetrustup** [outl1ne/nova-settings#130]
Hi there !

Thanks for the nice work of this package,

Would it be possible to have a cache feature for the settings ?
In my case I have a settings that's loaded on every pages but is a data that will not change that often.

I was thinking in the helpers.php to have a method params that will be the cache duration or something ?

```php
if (!function_exists('nova_get_setting')) {
    function nova_get_setting($settingKey, $default = null)
    {
        return NovaSettings::getSetting($settingKey, $default);
    }
}
```

Thank you !

**Comment by Tarpsvo** [comment]
Hi! You can create your own wrapping helper.

```php
function get_cached_setting($key, $default) {
  return Cache::remember($key, fn() => nova_get_setting($key, $default));
}
```
