### ISSUE TITLE
Am I the only one with 404?

### ISSUE THREAD

**Issue by HeadStudios** [outl1ne/nova-settings#133]
Just followed instructions Settings link is showing but when I click I get 404 error... no stack trace in laravel.log... did I miss something? Any input much appreciated. Thanks!

https://share.getcloudapp.com/eDuXNNo4

I'll log out and in to see if that fixes anything.

**Comment by HeadStudios** [comment]
Nvm I didn't have 
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Number;

inside NovaServiceProvider.php.. all good now!

**Comment by Tiththa** [comment]
If anyone encounters this even with fields imported, please clear the cache and everything should be fine

**Comment by sonaterai** [comment]
I got the same problem , but only on production..
all cache clear / route etc...
any idea ?

**Comment by HeadStudios** [comment]
> I got the same problem , but only on production.. all cache clear / route etc... any idea ?

Yep I think the environment or some other variable affects how nova settings is displayed - try changing the .env variable on live and see if that fixes it. I had to go into vendor folder to make the necessary adjustment - if you still have issues just search within that folder for any references to env(). Good luck!
