### ISSUE TITLE
mainMenu

### ISSUE THREAD

**Issue by merijnponzo** [outl1ne/nova-settings#134]
Hello,

With Nova 4.0, if i use a custom [menu](https://nova.laravel.com/docs/4.0/customization/menus.html)
```
Nova::mainMenu(function (Request $request) {
```
The settings won't show up in de sidebar, if i remove my custom menu i see the settings.

How can i add the settings to my custom menu?

thanks

**Comment by gauztech** [comment]
You can do it with a link directly to the Nova Settings url:

```
MenuSection::make('Configuration', [
    MenuItem::link('General Settings', 'nova-settings/general'),
])->icon('Cog'),
```

**Comment by merijnponzo** [comment]
Thanks!
