### ISSUE TITLE
Help text for fields don't appear

### ISSUE THREAD

**Issue by vodnicearv** [outl1ne/nova-settings#137]
help text for fields don't appear on page

**Comment by Tarpsvo** [comment]
Are you on the latest, 5.0.5, version?

**Comment by vodnicearv** [comment]
Yes

În mie., 5 oct. 2022 la 11:19 Tarvo R. ***@***.***> a scris:

**Comment by KasparRosin** [comment]
![image](https://user-images.githubusercontent.com/33309407/197218416-be1436c8-3389-4588-bd11-93ec86bf07e9.png)

Works for us. I suspect it might be caused by the field, if it's a third party field.
