### ISSUE TITLE
How to add Nova Settings to Nova menu?

### ISSUE THREAD

**Issue by makkinga** [outl1ne/nova-settings#148]
Using `Nova::mainMenu()`, what would be the best way to add Nova Settings? If possible at all.

I've tried adding this with no success:
```php
MenuItem::resource(\Outl1ne\NovaSettings\Nova\Resources\Settings::class)
```

**Comment by mstaack** [comment]
```
MenuSection::make('Settings')->path('/nova-settings/general')->icon('adjustments'),
```

**Comment by makkinga** [comment]
> ```
> MenuSection::make('Settings')->path('/nova-settings/general')->icon('adjustments'),
> ```

Thanks! That works 👍🏻  
For anyone needing this solution for multiple settings pages you need to specify the specific URL:

```php
MenuSection::make(__('Settings'), [
    MenuItem::make(__('Opening hours'))->path('/nova-settings/opening-hours'),
    MenuItem::make(__('Company information'))->path('/nova-settings/company-information'),
])->icon('adjustments')->collapsable()
```
