### ISSUE TITLE
Files do not get deleted, whenever you group the file field into a Panel

### ISSUE THREAD

**Issue by holyboly** [outl1ne/nova-settings#149]
If you group the file / image field into a Panel like this:

    Panel::make(__('CompanyInformation'), [
        Image::make(__('Logo'), 'company_logo')->prunable(),
    ]),

Then the `deleteImage` method from the `SettingsController` does not recognize the field, but the panel, which does not has an attribute with the field name:

    $field = collect(NovaSettings::getFields($pathName))->firstWhere('attribute', $fieldName);

Cannot overwrite the Controller myself afaik.

**Comment by hayatbiralem** [comment]
Same issue with the [eminiarts/nova-tabs](https://github.com/eminiarts/nova-tabs) field.

**Comment by Tarpsvo** [comment]
Fixed by @marttinnotta  in version 5.1.0. Good luck!
