### ISSUE TITLE
Unable to see settings menu when using Nova::mainMenu

### ISSUE THREAD

**Issue by iabduul7** [outl1ne/nova-settings#151]
My boot method looks something like this 

```
 public function boot()
    {
        parent::boot();

        Nova::mainMenu(function (Request $request) {
                    return [
                        MenuSection::make('Users', [
                            MenuItem::resource(User::class),
                        ])
                                   ->icon('user')
                                   ->collapsable(),
        
                    ];
                });
   }
```

Now if I add 
`
\Outl1ne\NovaSettings\NovaSettings::addSettingsFields([
                Text::make('Some setting', 'some_setting'),
            ]);
`
It does not show the settings menu unless I remove the `Nova::mainMenu()` function. Any solution for this?

**Comment by Tarpsvo** [comment]
https://github.com/outl1ne/nova-settings/issues/148
