### ISSUE TITLE
artisan test Error "Table 'test.nova_settings' doesn't exist"

### ISSUE THREAD

**Issue by JesperFiltenborg** [outl1ne/nova-settings#171]
When i run my test the nova_settings table is not migrating.

I can also run 
`artisan migrate --path=vendor/outl1ne/nova-settings/database/migrations --env=testing`
But nothing migrates.

The migrations work for the rest of the project.

**Comment by JesperFiltenborg** [comment]
My bad needed to add following in NovaServiceProvider
`if (Schema::hasTable('nova_settings')) {
            $this->novaSettings();
        }`

**Comment by arall** [comment]
I'm facing the same issue after migrating from Laravel 9 to 11, and I don't think your fix is the official way to go.
