### ISSUE TITLE
Save Settings button disabled or missing?

### ISSUE THREAD

**Issue by davidvexel** [outl1ne/nova-settings#173]
Hi!

For some reason my save settings button is not loading properly, I think I get this placeholder but not the actual submit button, I don't have any policies or permissions configuration in place, it's just a new Nova install. Any insight?

Thanks!

![image](https://github.com/outl1ne/nova-settings/assets/8060793/d1e4720d-db89-4d32-89cc-5c86a4c2815f)

**Comment by jackfishercf** [comment]
Im having the same issue

**Comment by karaOdin** [comment]
same issue, any help

**Comment by abyshakes** [comment]
Same issue here.. I had upgraded Laravel from 8 to 9 and 9 to 10 and also updated Nova.

**Comment by abyshakes** [comment]
I downgraded Nova to 4.27.14 and the Save button works.

**Comment by jackfishercf** [comment]
> I downgraded Nova to 4.27.14 and the Save button works.

that worked for me too

**Comment by davidvexel** [comment]
Nice thanks all, I confirmed it works downgrading nova, there may be something funky on version 4.28 and the submit button component of Nova.

**Comment by nathan-io** [comment]
Also experiencing this after upgrading Nova. Thanks for the PR @alancolant, hope it's merged it.

**Comment by nathan-io** [comment]
Also getting this with the latest Nova 4.29.2, I don't think this issue is going to resolve on its own.

For now, we've updated `composer.json` to use alancolant's fork:

```
...
"require": {
     ...
     "outl1ne/nova-settings": "dev-main",
     ...
```

```
    "repositories": [
        {
            "type": "composer",
            "url": "https://nova.laravel.com"
        },
        {
            "type":"vcs",
            "url":"https://github.com/alancolant/nova-settings"
        }
    ]
```

Then `composer update outl1ne/nova-settings`.

**Comment by alancolant** [comment]
Thank you, @nathan-io , for the details. 
I just want to clarify that I won't have the time to keep the fork updated if the plugin evolves on its own.
The only reliable long-term solution is for the pull request to be merged.

**Comment by vilhelmjosander** [comment]
Same issue here, would be great to get the PR merged.

**Comment by BeiAduo** [comment]
Now nova latest version still have this issues

**Comment by mstaack** [comment]
oh man, once again another nova<->nova-package issue... no saving for now i guess :/

**Comment by alancolant** [comment]
@davidvexel 
I create PR in https://github.com/JeffBeltran/sanctum-tokens with same fix

**Comment by mstaack** [comment]
thank you! fix works...saving is back again 🚀
