### ISSUE TITLE
Save button is barely visible

### ISSUE THREAD

**Issue by bilogic** [outl1ne/nova-settings#179]
![image](https://github.com/outl1ne/nova-settings/assets/946010/0f523872-3ec2-4de8-b2fc-fc050d8534e1)

The save button is barely visible in light and dark theme

**Comment by oakyydev** [comment]
This is an issue with your project. Its works well in my project.

Maybe publish your nova assets again?

`php artisan nova:publish` / `sail artisan nova:publish`
