### ISSUE TITLE
Version 6 has JS error when loading: "LaravelNova" not found with nova 4

### ISSUE THREAD

**Issue by bmellink** [outl1ne/nova-settings#194]
Version 6 references a JS variable called LaravelNova which is not available in nova 4 preventing the file nova-settings.js to load. Temporary locking the nova-settings version to 5.2.4 in composer.json solves the issue
`
"outl1ne/nova-settings": "5.2.4",
`

**Comment by Tarpsvo** [comment]
Removed Nova 4.x compatibility from 6.0. Thanks!
