### ISSUE TITLE
LaravelNovaUi is not defined

### ISSUE THREAD

**Issue by Mksafi-codeloops** [outl1ne/nova-settings#197]
<img width="638" alt="Screenshot 2024-12-19 at 9 07 31 PM" src="https://github.com/user-attachments/assets/f488c56b-2864-4d05-9491-90c8e703cfbf" />

Hello Sir 
I faced this problem twice in an old and new project, which caused breaking Nova and showing a blank page.
        "outl1ne/nova-settings": "^5.2",

**Comment by Tarpsvo** [comment]
Oooof, I think I released the wrong branch for Nova v4. :( Fixed now, same release number.
