### ISSUE TITLE
About the case when field labels use localization 

### ISSUE THREAD

**Issue by medvinator** [outl1ne/nova-settings#53]
Example of registering fields from the documentation:
```php
\OptimistDigital\NovaSettings\NovaSettings::addSettingsFields([
    Text::make('Some setting', 'some_setting'),
    Number::make('A number', 'a_number'),
]);
```

If the field labels use localization, then an example would be like this:
```php
\OptimistDigital\NovaSettings\NovaSettings::addSettingsFields([
    Text::make(__('Some setting'), 'some_setting'),
    Number::make(__('A number'), 'a_number'),
]);
```

But if localization is determined by middleware (from browser or user settings), then label localization won't work. 
Because the code from `\App\Providers\NovaServiceProvider::boot` will work before middleware.

For the fields to become localized, you need to set the settings fields when fired `\Laravel\Nova\Events\ServingNova` event, like this 
```php
use Laravel\Nova\Nova;
use OptimistDigital\NovaSettings\NovaSettings;
...

Nova::serving(function () {
    \OptimistDigital\NovaSettings\NovaSettings::addSettingsFields([
        Text::make(__('Some setting'), 'some_setting'),
        Number::make(__('A number'), 'a_number'),
    ]);
});
```

This is not a bug, just a note 🙂

**Comment by etionic-gdiez** [comment]
I found that casts does not works when you pass as the second parameter:
```php
Nova::serving(function () {
    NovaSettings::addSettingsFields([], $casts);
});
```
To get it works you must not use second parameter and instead write outer of Nova::serving() function, like this:
```php
Nova::serving(function () {
    NovaSettings::addSettingsFields([]);
});
NovaSettings::addCasts(['key' => 'boolean']);
```

Thanks a lot!

**Comment by Tarpsvo** [comment]
Yeah, if we wait for the Nova::serving to run, the casts might not really be there before that event.  That is the correct solution in that case.
